name: Deploy Static Website to Lightsail

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload website to server
        uses: burnett01/rsync-deployments@8.1.0
        with:
          switches: -avzr --delete --exclude=".git*" --exclude=".github"
          path: ./
          remote_path: /var/www/site1/
          remote_host: ${{ secrets.LIGHTSAIL_HOST }}
          remote_user: ${{ secrets.LIGHTSAIL_USER }}
          remote_key: ${{ secrets.LIGHTSAIL_SSH_KEY }}

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.LIGHTSAIL_HOST }}
          username: ${{ secrets.LIGHTSAIL_USER }}
          key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          script: |
            sudo nginx -t
            sudo systemctl reload nginx
            echo "âœ… Deploy done"
